version: '3.8'

volumes:
  static_volume:
  postgres_data:
  media_volume:

services:
  db:
    image: postgres:12
    restart: always
    container_name: postgres
    environment:
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: sorochinskii/foodgram:latest
    container_name: foodgram
    restart: always
    volumes:
      - ./static_volume:/code/files/static/
      - ./media_volume:/code/files/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.8
    container_name: webserver
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static_volume:/code/files/static
      - ./media_volume:/code/files/media
    ports:
      - "80:80"
    depends_on:
      - web
