# Generated by Django 2.2 on 2021-02-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('product',), 'verbose_name': 'Количество ингредиентов'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='oucmt'),
        ),
    ]
