# Generated by Django 3.1.4 on 2021-04-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210427_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='uqzgs', verbose_name='слаг тэга'),
        ),
    ]
