# Generated by Django 3.1.4 on 2021-04-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210426_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='tmtxj', verbose_name='слаг тэга'),
        ),
    ]
