# Generated by Django 2.2 on 2021-04-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210427_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='jytjz', verbose_name='слаг тэга'),
        ),
    ]
