# Generated by Django 3.1.4 on 2021-04-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210409_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='rhvdi', verbose_name='слаг тэга'),
        ),
    ]
