# Generated by Django 2.2 on 2021-04-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210409_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='kykxd', verbose_name='слаг тэга'),
        ),
    ]
