# Generated by Django 3.1.4 on 2021-04-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210410_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='vdvwe', verbose_name='слаг тэга'),
        ),
    ]
