# Generated by Django 2.2 on 2021-04-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20210410_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='yznkv', verbose_name='слаг тэга'),
        ),
    ]
