# Generated by Django 3.1.4 on 2021-04-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20210423_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='flfdi', verbose_name='слаг тэга'),
        ),
    ]
