# Generated by Django 2.2 on 2021-03-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20210322_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='fvlju'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'color', 'color_slug', 'slug')},
        ),
    ]
