# Generated by Django 2.2 on 2021-03-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20210329_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color_slug',
            field=models.SlugField(default='#000000', verbose_name='слаг цвета'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='mecyo', verbose_name='слаг тэга'),
        ),
    ]
