# Generated by Django 2.2 on 2021-03-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20210331_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='recipes',
            field=models.ManyToManyField(related_name='favorites', to='recipes.Recipe', verbose_name='рецепты'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='gnsqv', verbose_name='слаг тэга'),
        ),
    ]
