# Generated by Django 2.2 on 2021-03-31 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_auto_20210331_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='recipes',
        ),
        migrations.AddField(
            model_name='favorite',
            name='recipes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='recipes.Recipe', verbose_name='рецепты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='mrvjr', verbose_name='слаг тэга'),
        ),
    ]
