# Generated by Django 2.2 on 2021-03-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_auto_20210331_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='bkctl', verbose_name='слаг тэга'),
        ),
    ]
