# Generated by Django 2.2 on 2021-04-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_auto_20210401_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='orcrx', verbose_name='слаг тэга'),
        ),
    ]
